// ⚠️ 本文件由 scripts/generate-frontend-contract.mjs 生成，请勿手改。
// 改完请重跑 `node scripts/generate-frontend-contract.mjs`（docs/06 §7 禁止手写 DTO）。

/**
 * 权限点常量（docs/07 §2.2 的第三处，与后端 registry 和 `permissions` 表 seed 保持一致）。
 *
 * ⚠️ 三处一致是**闸门 1 的硬要求**（docs/07 §2.2「三处不一致视为闸门 1 失败」）：
 *   1. `backend/app/common/permissions_registry.py`（单一来源）
 *   2. `permissions` 表的 seed（迁移 0002 与 `seed_baseline`）
 *   3. 本文件
 *
 * 后端 `tests/modules/test_permission_registry.py::test_frontend_constants_match_registry`
 * 会断言本文件的 code 集合与 registry **完全相等**，少一个就红。
 *
 * 页面用 `v-can` 指令控制显隐，**后端仍然兜底 403** —— 前端隐藏不是安全。
 */

/** 全部权限点 code。类型由数组推导，新增一档不需要改别处。 */
export const PERMISSION_CODES = [
  'base:category:manage',
  'base:create',
  'base:delete',
  'base:disable',
  'base:export',
  'base:import',
  'base:operation:manage',
  'base:rate_template:manage',
  'base:ratio:manage',
  'base:read',
  'base:update',
  'bundling:approve',
  'bundling:cancel',
  'bundling:code:void',
  'bundling:create',
  'bundling:export',
  'bundling:print',
  'bundling:read',
  'bundling:reject',
  'bundling:reverse',
  'bundling:submit',
  'bundling:update',
  'bundling:withdraw',
  'cutting:approve',
  'cutting:cancel',
  'cutting:create',
  'cutting:export',
  'cutting:import',
  'cutting:read',
  'cutting:reject',
  'cutting:reverse',
  'cutting:submit',
  'cutting:trace:read',
  'cutting:update',
  'cutting:withdraw',
  'finance:ap:read',
  'finance:ar:read',
  'finance:export',
  'finance:import',
  'finance:payment',
  'finance:payment:reverse',
  'finance:period:close',
  'finance:period:reopen',
  'finance:receipt',
  'finance:receipt:reverse',
  'finance:settle',
  'finance:statement',
  'finance:voucher:create',
  'finance:voucher:post',
  'finance:voucher:read',
  'finance:voucher:reverse',
  'finance:voucher:update',
  'payroll:approve',
  'payroll:cancel',
  'payroll:create',
  'payroll:export',
  'payroll:pay',
  'payroll:period:manage',
  'payroll:read',
  'payroll:reject',
  'payroll:reverse',
  'payroll:settle',
  'payroll:submit',
  'payroll:update',
  'payroll:withdraw',
  'piecework:count',
  'piecework:export',
  'piecework:manual',
  'piecework:rate:manage',
  'piecework:read',
  'piecework:reverse',
  'purchase:approve',
  'purchase:arrival',
  'purchase:arrival:reverse',
  'purchase:cancel',
  'purchase:create',
  'purchase:export',
  'purchase:import',
  'purchase:ledger:read',
  'purchase:read',
  'purchase:reject',
  'purchase:reverse',
  'purchase:submit',
  'purchase:update',
  'sales:approve',
  'sales:cancel',
  'sales:export',
  'sales:import',
  'sales:order:create',
  'sales:read',
  'sales:reject',
  'sales:reverse',
  'sales:ship',
  'sales:submit',
  'sales:update',
  'sales:withdraw',
  'self:payroll:read',
  'self:piecework:bind',
  'self:piecework:read',
  'self:profile:read',
  'stock:approve',
  'stock:cancel',
  'stock:cost:view',
  'stock:create',
  'stock:export',
  'stock:in',
  'stock:in:manual',
  'stock:out',
  'stock:read',
  'stock:reverse',
  'stock:stocktake',
  'stock:submit',
  'stock:transfer',
  'stock:update',
  'stock:wip:read',
  'system:config:manage',
  'system:export:manage',
  'system:import:manage',
  'system:log:view',
  'system:role:manage',
  'system:user:manage',
  'system:workshop:manage',
] as const

export type PermissionCode = (typeof PERMISSION_CODES)[number]

/** 权限点 → 界面名（后端 `permissions.name` 的快照，只读不做判断）。 */
export const PERMISSION_NAMES: Readonly<Record<PermissionCode, string>> = {
  'base:category:manage': '基础资料·商品分类维护',
  'base:create': '基础资料·新建',
  'base:delete': '基础资料·删除',
  'base:disable': '基础资料·停用',
  'base:export': '基础资料·导出',
  'base:import': '基础资料·导入',
  'base:operation:manage': '基础资料·工序主数据维护',
  'base:rate_template:manage': '基础资料·款号工序模板复制',
  'base:ratio:manage': '基础资料·尺码比例维护',
  'base:read': '基础资料·查看',
  'base:update': '基础资料·修改',
  'bundling:approve': '打菲·审核',
  'bundling:cancel': '打菲·作废',
  'bundling:code:void': '打菲·作废打菲码',
  'bundling:create': '打菲·新建',
  'bundling:export': '打菲·导出',
  'bundling:print': '打菲·打印',
  'bundling:read': '打菲·查看',
  'bundling:reject': '打菲·驳回',
  'bundling:reverse': '打菲·反审核',
  'bundling:submit': '打菲·提交',
  'bundling:update': '打菲·修改',
  'bundling:withdraw': '打菲·撤回',
  'cutting:approve': '裁剪·审核',
  'cutting:cancel': '裁剪·作废',
  'cutting:create': '裁剪·新建',
  'cutting:export': '裁剪·导出',
  'cutting:import': '裁剪·导入',
  'cutting:read': '裁剪·查看',
  'cutting:reject': '裁剪·驳回',
  'cutting:reverse': '裁剪·反审核',
  'cutting:submit': '裁剪·提交',
  'cutting:trace:read': '裁剪·生产溯源查看',
  'cutting:update': '裁剪·修改',
  'cutting:withdraw': '裁剪·撤回',
  'finance:ap:read': '往来/财务·应付查看',
  'finance:ar:read': '往来/财务·应收查看',
  'finance:export': '往来/财务·导出',
  'finance:import': '往来/财务·导入',
  'finance:payment': '往来/财务·付款',
  'finance:payment:reverse': '往来/财务·付款红冲',
  'finance:period:close': '往来/财务·会计期间关账',
  'finance:period:reopen': '往来/财务·会计期间反关账',
  'finance:receipt': '往来/财务·收款',
  'finance:receipt:reverse': '往来/财务·收款红冲',
  'finance:settle': '往来/财务·结算',
  'finance:statement': '往来/财务·对账单',
  'finance:voucher:create': '往来/财务·新建凭证',
  'finance:voucher:post': '往来/财务·凭证过账',
  'finance:voucher:read': '往来/财务·凭证查看',
  'finance:voucher:reverse': '往来/财务·凭证红冲',
  'finance:voucher:update': '往来/财务·修改凭证',
  'payroll:approve': '工资·审核',
  'payroll:cancel': '工资·作废',
  'payroll:create': '工资·新建',
  'payroll:export': '工资·导出',
  'payroll:pay': '工资·发放',
  'payroll:period:manage': '工资·结算周期维护',
  'payroll:read': '工资·查看',
  'payroll:reject': '工资·驳回',
  'payroll:reverse': '工资·反审核',
  'payroll:settle': '工资·结算',
  'payroll:submit': '工资·提交',
  'payroll:update': '工资·修改',
  'payroll:withdraw': '工资·撤回',
  'piecework:count': '计件·扫码计件',
  'piecework:export': '计件·导出',
  'piecework:manual': '计件·手工补录',
  'piecework:rate:manage': '计件·单价维护',
  'piecework:read': '计件·查看',
  'piecework:reverse': '计件·反审核',
  'purchase:approve': '采购·审核',
  'purchase:arrival': '采购·到货登记',
  'purchase:arrival:reverse': '采购·到货红冲',
  'purchase:cancel': '采购·作废',
  'purchase:create': '采购·新建',
  'purchase:export': '采购·导出',
  'purchase:import': '采购·导入',
  'purchase:ledger:read': '采购·采购台账查看',
  'purchase:read': '采购·查看',
  'purchase:reject': '采购·驳回',
  'purchase:reverse': '采购·反审核',
  'purchase:submit': '采购·提交',
  'purchase:update': '采购·修改',
  'sales:approve': '销售·审核',
  'sales:cancel': '销售·作废',
  'sales:export': '销售·导出',
  'sales:import': '销售·导入',
  'sales:order:create': '销售·新建订单',
  'sales:read': '销售·查看',
  'sales:reject': '销售·驳回',
  'sales:reverse': '销售·反审核',
  'sales:ship': '销售·发货',
  'sales:submit': '销售·提交',
  'sales:update': '销售·修改',
  'sales:withdraw': '销售·撤回',
  'self:payroll:read': '员工自助·我的工资',
  'self:piecework:bind': '员工自助·绑定计件工序',
  'self:piecework:read': '员工自助·piecework:read',
  'self:profile:read': '员工自助·个人信息查看',
  'stock:approve': '库存·审核',
  'stock:cancel': '库存·作废',
  'stock:cost:view': '库存·查看成本',
  'stock:create': '库存·新建',
  'stock:export': '库存·导出',
  'stock:in': '库存·入库',
  'stock:in:manual': '库存·手动完单入库',
  'stock:out': '库存·出库',
  'stock:read': '库存·查看',
  'stock:reverse': '库存·反审核',
  'stock:stocktake': '库存·盘点',
  'stock:submit': '库存·提交',
  'stock:transfer': '库存·调拨',
  'stock:update': '库存·修改',
  'stock:wip:read': '库存·在制品查看',
  'system:config:manage': '系统·系统配置管理',
  'system:export:manage': '系统·导出总开关',
  'system:import:manage': '系统·导入总开关',
  'system:log:view': '系统·日志查看',
  'system:role:manage': '系统·角色管理',
  'system:user:manage': '系统·用户管理',
  'system:workshop:manage': '系统·车间管理',
}

/**
 * 逐个权限点的具名常量。
 *
 * 为什么除了 `PERMISSION_CODES` 还要这一份：模板里写 `v-can="PERM.BASE_CREATE"`
 * 比写裸字符串 `'base:create'` 更难打错 —— 裸字符串写错了要等运行时 403 才发现，
 * 具名常量写错了编译就红。
 */
export const PERM = {
  BASE_CATEGORY_MANAGE: 'base:category:manage',
  BASE_CREATE: 'base:create',
  BASE_DELETE: 'base:delete',
  BASE_DISABLE: 'base:disable',
  BASE_EXPORT: 'base:export',
  BASE_IMPORT: 'base:import',
  BASE_OPERATION_MANAGE: 'base:operation:manage',
  BASE_RATE_TEMPLATE_MANAGE: 'base:rate_template:manage',
  BASE_RATIO_MANAGE: 'base:ratio:manage',
  BASE_READ: 'base:read',
  BASE_UPDATE: 'base:update',
  BUNDLING_APPROVE: 'bundling:approve',
  BUNDLING_CANCEL: 'bundling:cancel',
  BUNDLING_CODE_VOID: 'bundling:code:void',
  BUNDLING_CREATE: 'bundling:create',
  BUNDLING_EXPORT: 'bundling:export',
  BUNDLING_PRINT: 'bundling:print',
  BUNDLING_READ: 'bundling:read',
  BUNDLING_REJECT: 'bundling:reject',
  BUNDLING_REVERSE: 'bundling:reverse',
  BUNDLING_SUBMIT: 'bundling:submit',
  BUNDLING_UPDATE: 'bundling:update',
  BUNDLING_WITHDRAW: 'bundling:withdraw',
  CUTTING_APPROVE: 'cutting:approve',
  CUTTING_CANCEL: 'cutting:cancel',
  CUTTING_CREATE: 'cutting:create',
  CUTTING_EXPORT: 'cutting:export',
  CUTTING_IMPORT: 'cutting:import',
  CUTTING_READ: 'cutting:read',
  CUTTING_REJECT: 'cutting:reject',
  CUTTING_REVERSE: 'cutting:reverse',
  CUTTING_SUBMIT: 'cutting:submit',
  CUTTING_TRACE_READ: 'cutting:trace:read',
  CUTTING_UPDATE: 'cutting:update',
  CUTTING_WITHDRAW: 'cutting:withdraw',
  FINANCE_AP_READ: 'finance:ap:read',
  FINANCE_AR_READ: 'finance:ar:read',
  FINANCE_EXPORT: 'finance:export',
  FINANCE_IMPORT: 'finance:import',
  FINANCE_PAYMENT: 'finance:payment',
  FINANCE_PAYMENT_REVERSE: 'finance:payment:reverse',
  FINANCE_PERIOD_CLOSE: 'finance:period:close',
  FINANCE_PERIOD_REOPEN: 'finance:period:reopen',
  FINANCE_RECEIPT: 'finance:receipt',
  FINANCE_RECEIPT_REVERSE: 'finance:receipt:reverse',
  FINANCE_SETTLE: 'finance:settle',
  FINANCE_STATEMENT: 'finance:statement',
  FINANCE_VOUCHER_CREATE: 'finance:voucher:create',
  FINANCE_VOUCHER_POST: 'finance:voucher:post',
  FINANCE_VOUCHER_READ: 'finance:voucher:read',
  FINANCE_VOUCHER_REVERSE: 'finance:voucher:reverse',
  FINANCE_VOUCHER_UPDATE: 'finance:voucher:update',
  PAYROLL_APPROVE: 'payroll:approve',
  PAYROLL_CANCEL: 'payroll:cancel',
  PAYROLL_CREATE: 'payroll:create',
  PAYROLL_EXPORT: 'payroll:export',
  PAYROLL_PAY: 'payroll:pay',
  PAYROLL_PERIOD_MANAGE: 'payroll:period:manage',
  PAYROLL_READ: 'payroll:read',
  PAYROLL_REJECT: 'payroll:reject',
  PAYROLL_REVERSE: 'payroll:reverse',
  PAYROLL_SETTLE: 'payroll:settle',
  PAYROLL_SUBMIT: 'payroll:submit',
  PAYROLL_UPDATE: 'payroll:update',
  PAYROLL_WITHDRAW: 'payroll:withdraw',
  PIECEWORK_COUNT: 'piecework:count',
  PIECEWORK_EXPORT: 'piecework:export',
  PIECEWORK_MANUAL: 'piecework:manual',
  PIECEWORK_RATE_MANAGE: 'piecework:rate:manage',
  PIECEWORK_READ: 'piecework:read',
  PIECEWORK_REVERSE: 'piecework:reverse',
  PURCHASE_APPROVE: 'purchase:approve',
  PURCHASE_ARRIVAL: 'purchase:arrival',
  PURCHASE_ARRIVAL_REVERSE: 'purchase:arrival:reverse',
  PURCHASE_CANCEL: 'purchase:cancel',
  PURCHASE_CREATE: 'purchase:create',
  PURCHASE_EXPORT: 'purchase:export',
  PURCHASE_IMPORT: 'purchase:import',
  PURCHASE_LEDGER_READ: 'purchase:ledger:read',
  PURCHASE_READ: 'purchase:read',
  PURCHASE_REJECT: 'purchase:reject',
  PURCHASE_REVERSE: 'purchase:reverse',
  PURCHASE_SUBMIT: 'purchase:submit',
  PURCHASE_UPDATE: 'purchase:update',
  SALES_APPROVE: 'sales:approve',
  SALES_CANCEL: 'sales:cancel',
  SALES_EXPORT: 'sales:export',
  SALES_IMPORT: 'sales:import',
  SALES_ORDER_CREATE: 'sales:order:create',
  SALES_READ: 'sales:read',
  SALES_REJECT: 'sales:reject',
  SALES_REVERSE: 'sales:reverse',
  SALES_SHIP: 'sales:ship',
  SALES_SUBMIT: 'sales:submit',
  SALES_UPDATE: 'sales:update',
  SALES_WITHDRAW: 'sales:withdraw',
  SELF_PAYROLL_READ: 'self:payroll:read',
  SELF_PIECEWORK_BIND: 'self:piecework:bind',
  SELF_PIECEWORK_READ: 'self:piecework:read',
  SELF_PROFILE_READ: 'self:profile:read',
  STOCK_APPROVE: 'stock:approve',
  STOCK_CANCEL: 'stock:cancel',
  STOCK_COST_VIEW: 'stock:cost:view',
  STOCK_CREATE: 'stock:create',
  STOCK_EXPORT: 'stock:export',
  STOCK_IN: 'stock:in',
  STOCK_IN_MANUAL: 'stock:in:manual',
  STOCK_OUT: 'stock:out',
  STOCK_READ: 'stock:read',
  STOCK_REVERSE: 'stock:reverse',
  STOCK_STOCKTAKE: 'stock:stocktake',
  STOCK_SUBMIT: 'stock:submit',
  STOCK_TRANSFER: 'stock:transfer',
  STOCK_UPDATE: 'stock:update',
  STOCK_WIP_READ: 'stock:wip:read',
  SYSTEM_CONFIG_MANAGE: 'system:config:manage',
  SYSTEM_EXPORT_MANAGE: 'system:export:manage',
  SYSTEM_IMPORT_MANAGE: 'system:import:manage',
  SYSTEM_LOG_VIEW: 'system:log:view',
  SYSTEM_ROLE_MANAGE: 'system:role:manage',
  SYSTEM_USER_MANAGE: 'system:user:manage',
  SYSTEM_WORKSHOP_MANAGE: 'system:workshop:manage',
} as const satisfies Record<string, PermissionCode>

/** 内置角色 code（docs/07 §2.3）。 */
export const ROLE_CODES = [
  'super_admin',
  'factory_manager',
  'workshop_supervisor',
  'line_leader',
  'warehouse_keeper',
  'accountant',
  'purchaser',
  'merchandiser',
  'piecework_settler',
  'employee',
] as const

export type RoleCode = (typeof ROLE_CODES)[number]

/**
 * 角色 → 该角色实际拥有的权限点。
 *
 * ⚠️ 这是**快照**，不是运行时真相：用户在后台改了角色授权后这里就过时了。
 * 因此**只用于测试夹具与「能不能看到入口」的预判**，真正的鉴权在后端
 * （`AuthContext.has()` 每次请求查库，docs/07 §1.1）。用它做前端唯一判据 = 越权。
 */
export const ROLE_PERMISSIONS: Readonly<Record<RoleCode, readonly PermissionCode[]>> = {
  super_admin: [
    'base:category:manage',
    'base:create',
    'base:delete',
    'base:disable',
    'base:export',
    'base:import',
    'base:operation:manage',
    'base:rate_template:manage',
    'base:ratio:manage',
    'base:read',
    'base:update',
    'bundling:approve',
    'bundling:cancel',
    'bundling:code:void',
    'bundling:create',
    'bundling:export',
    'bundling:print',
    'bundling:read',
    'bundling:reject',
    'bundling:reverse',
    'bundling:submit',
    'bundling:update',
    'bundling:withdraw',
    'cutting:approve',
    'cutting:cancel',
    'cutting:create',
    'cutting:export',
    'cutting:import',
    'cutting:read',
    'cutting:reject',
    'cutting:reverse',
    'cutting:submit',
    'cutting:trace:read',
    'cutting:update',
    'cutting:withdraw',
    'finance:ap:read',
    'finance:ar:read',
    'finance:export',
    'finance:import',
    'finance:payment',
    'finance:payment:reverse',
    'finance:period:close',
    'finance:period:reopen',
    'finance:receipt',
    'finance:receipt:reverse',
    'finance:settle',
    'finance:statement',
    'finance:voucher:create',
    'finance:voucher:post',
    'finance:voucher:read',
    'finance:voucher:reverse',
    'finance:voucher:update',
    'payroll:approve',
    'payroll:cancel',
    'payroll:create',
    'payroll:export',
    'payroll:pay',
    'payroll:period:manage',
    'payroll:read',
    'payroll:reject',
    'payroll:reverse',
    'payroll:settle',
    'payroll:submit',
    'payroll:update',
    'payroll:withdraw',
    'piecework:count',
    'piecework:export',
    'piecework:manual',
    'piecework:rate:manage',
    'piecework:read',
    'piecework:reverse',
    'purchase:approve',
    'purchase:arrival',
    'purchase:arrival:reverse',
    'purchase:cancel',
    'purchase:create',
    'purchase:export',
    'purchase:import',
    'purchase:ledger:read',
    'purchase:read',
    'purchase:reject',
    'purchase:reverse',
    'purchase:submit',
    'purchase:update',
    'sales:approve',
    'sales:cancel',
    'sales:export',
    'sales:import',
    'sales:order:create',
    'sales:read',
    'sales:reject',
    'sales:reverse',
    'sales:ship',
    'sales:submit',
    'sales:update',
    'sales:withdraw',
    'self:payroll:read',
    'self:piecework:bind',
    'self:piecework:read',
    'self:profile:read',
    'stock:approve',
    'stock:cancel',
    'stock:cost:view',
    'stock:create',
    'stock:export',
    'stock:in',
    'stock:in:manual',
    'stock:out',
    'stock:read',
    'stock:reverse',
    'stock:stocktake',
    'stock:submit',
    'stock:transfer',
    'stock:update',
    'stock:wip:read',
    'system:config:manage',
    'system:export:manage',
    'system:import:manage',
    'system:log:view',
    'system:role:manage',
    'system:user:manage',
    'system:workshop:manage',
  ],
  factory_manager: [
    'base:read',
    'bundling:approve',
    'bundling:read',
    'bundling:reject',
    'cutting:approve',
    'cutting:read',
    'cutting:reject',
    'finance:ap:read',
    'finance:ar:read',
    'payroll:approve',
    'payroll:read',
    'piecework:read',
    'purchase:read',
    'sales:read',
    'stock:read',
    'system:log:view',
  ],
  workshop_supervisor: [
    'base:ratio:manage',
    'base:read',
    'base:update',
    'bundling:approve',
    'bundling:print',
    'bundling:read',
    'bundling:reject',
    'cutting:approve',
    'cutting:read',
    'cutting:reject',
    'piecework:read',
    'purchase:read',
    'stock:read',
  ],
  line_leader: ['base:read', 'bundling:read', 'cutting:read', 'piecework:read'],
  warehouse_keeper: [
    'base:create',
    'base:export',
    'base:import',
    'base:read',
    'base:update',
    'purchase:read',
    'stock:in',
    'stock:out',
    'stock:read',
    'stock:stocktake',
    'stock:transfer',
  ],
  accountant: [
    'base:create',
    'base:export',
    'base:read',
    'base:update',
    'finance:ap:read',
    'finance:ar:read',
    'finance:export',
    'finance:payment',
    'finance:period:close',
    'finance:period:reopen',
    'finance:receipt',
    'finance:settle',
    'finance:statement',
    'finance:voucher:create',
    'finance:voucher:post',
    'finance:voucher:read',
    'finance:voucher:reverse',
    'finance:voucher:update',
    'purchase:read',
    'sales:read',
    'stock:read',
  ],
  purchaser: [
    'base:create',
    'base:export',
    'base:import',
    'base:read',
    'base:update',
    'purchase:approve',
    'purchase:arrival',
    'purchase:arrival:reverse',
    'purchase:create',
    'purchase:export',
    'purchase:import',
    'purchase:ledger:read',
    'purchase:read',
    'purchase:submit',
    'purchase:update',
  ],
  merchandiser: ['base:read', 'bundling:read', 'cutting:read', 'sales:read'],
  piecework_settler: [
    'base:export',
    'base:rate_template:manage',
    'base:read',
    'base:update',
    'payroll:create',
    'payroll:export',
    'payroll:period:manage',
    'payroll:read',
    'payroll:settle',
    'payroll:submit',
    'payroll:update',
    'piecework:export',
    'piecework:rate:manage',
    'piecework:read',
  ],
  employee: [],
}
